### ISSUE TITLE
Allow TcDbTester to use multiple schemas in Testcontainer

### ISSUE THREAD

**Issue by dschulten** [bootique/bootique-jdbc#130]
Running an oraclexe testcontainer is not exactly lightweight, and  it gets worse if you need to test interaction of an application with multiple databases (three in our case).

Is it possible, or can we make it possible to create only one testcontainer, but use multiple schemas within the same dbms instance?

It appears that for the moment, every TcDbTestContainer creates its own dbms:

```
@BQTestTool
static final DbTester tester = TcDbTester
        .db("jdbc:tc:postgresql:11:///")
        .initDBWithLiquibaseChangelog("classpath:my/app/postgres-changelog.yml");
```

**Comment by andrus** [comment]
The DB you create within a container is a regular database, so you should be able to create multiple schemas via Liquibase. Also recommed using global scope (`@BQTestTool(BQTestScope.GLOBAL)`), so that you can have a single instance shared by all subclasses of a base test class.

**Comment by dschulten** [comment]
We have three Oracle schemas, each with their own liquibase changelogs, which need to be accessed with different users (is how Oracle treats schemas - a schema is a user). I cannot change the liquibase files. The liquibase files define items with conflicting names, e.g. constraints having the same name.

Therefore I cannot do this:

    @BQTestTool(BQTestScope.GLOBAL)
    static final DbTester tester = TcDbTester.db(oracle)
            .initDBWithLiquibaseChangelog("classpath:changelog-schema1.yml")
            .initDBWithLiquibaseChangelog("classpath:changelog-schema2.yml")
            .initDBWithLiquibaseChangelog("classpath:changelog-schema3.yml")


The test needs to select data from two of the schemas and transfer them to the third schema (it is a camel application).

With JUnit4, I was able to do this by creating three BQRuntimes, each with its own application.yml containing a liquibase definition for a separate datasource having a different user. 

For each BQRuntime I was able to ask for its DatabaseChannel using DatabaseChannel.get(runtimeSchema1) etc. in the test. How can I replicate this with TcDbTester?

**Comment by andrus** [comment]
I just spoke to the Testcontainers folks, and was about to propose a similar solution, but you already figured the details :)

**Comment by andrus** [comment]
Could you link the StackOverflow thread here please?

**Comment by dschulten** [comment]
Here is the stackoverflow: https://stackoverflow.com/q/77267140/743507

**Comment by andrus** [comment]
Great. I guess this task can be closed.
