### ISSUE TITLE
Bootique with servlets/jsp project?

### ISSUE THREAD

**Issue by raulvillalbamedina** [bootique/bootique-jdbc#18]
Hi I am working in a project with servlets/jsp and I am testing bootique.
I start the server but i have not pages.
Some example?

**Comment by andrus** [comment]
[Bootique jetty docs](http://bootique.io/docs/0/bootique-jetty-docs/index.html#d0e59) show how to add servlets. We haven't tested JSP support yet (we might implement it if there's demand), but servlets work just fine. 

Also note that you opened this task under bootique-jdbc module. For further questions I recommend going to [Bootique forum](https://groups.google.com/forum/#!forum/bootique-user) (where we can discuss JSP support among other things) or open issues under [bootique-jetty](https://github.com/bootique/bootique-jetty).
