### ISSUE TITLE
Add support for HikariCP

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-jdbc#34]
[HikariCP](https://github.com/brettwooldridge/HikariCP) is pretty popular so Bootique should add support for it along with currently exclusive tomcat-jdbc.
This will probably require some abstract pool API at boutique-jdbc level and separate modules for pool implementations.

**Comment by ebondareva** [comment]
**Subtasks:**

1. Extract TomcatCP as a separate module #48 
1.1. Leave Jdbc module purely abstract
2. Add HikariCP as a separate module #51
3. Make bq-jdbc-test common
4. Make bq-jdbc-instrumented common, having extracted metrics as a plugin
