### ISSUE TITLE
Extract Tomcat DataSource integration into a separate module

### ISSUE THREAD

**Issue by ebondareva** [bootique/bootique-jdbc#48]
Extract `TomcatJdbcModule` as a separate module, leaving `JdbcModule` purely abstract.
Subtask for Add support for HikariCP #34.

## Upgrade Notes

This task breaks backwards compatibility for all JDBC applications. On startup you will see an error like this:

```
No concrete 'bootique-jdbc' implementations found. You will need to add one 
(such as 'bootique-jdbc-tomcat', etc.) as an application dependency.
``` 
You will need to do exactly as suggested, i.e. add the following dependency to your `pom.xml`:
```xml
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-tomcat</artifactId>
    <scope>compile</scope>
</dependency>
```
The original `bootique-jdbc` is now a transitive dependency of the new `bootique-jdbc-tomcat`, so you may remove explicit `bootique-jdbc` import. 

If you are using `bootique-jdbc-instrumented` (i.e. JDBC with metrics), import a different dependency:
```xml
<dependency>
    <groupId>io.bootique.jdbc</groupId>
    <artifactId>bootique-jdbc-instrumented-tomcat</artifactId>
    <scope>compile</scope>
</dependency>
```

**Comment by andrus** [comment]
Let's make sure that we give users some heads up before we commit this. It will affect every single app using 0.24-SNAPSHOT.
