### ISSUE TITLE
Auto detection of an available connection pool 

### ISSUE THREAD

**Issue by ebondareva** [bootique/bootique-jdbc#62]
To keep backward compatibility with 0.24, any plugged in CP must be chosen as default one. 
Basic cases:
1. cp1 plugged in -> configs without 'type' are mapped on the cp1 type, the others are to be checked if their 'type' is the cp1, throw exception otherwise.
2. cp1, cp2 -> configs without 'type' mapped on Tomcat as the default cp, the others are mapped on the cp defined in their config.
3. no cp -> error

**Parent issue** #48

**Comment by andrus** [comment]
As we discussed offline, #2 should be something like this: "cp1, cp2 -> configs without 'type' generate an exception, with type - mapped to CP type"

**Comment by ebondareva** [comment]
Jackson issue revealed on Travis build is fixed in [#193](https://github.com/bootique/bootique/issues/193)

**Comment by ebondareva** [comment]
An improvement is to be implement in #72
