### ISSUE TITLE
bootique-jdbc-test: TableMatcher can't properly convert CSV data types for comparison

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jdbc#90]
`TableMatcher.assertMatchesCsv()` from `bootique-jdbc-test` can't always properly convert CSV data types for comparison. So if e.g. the table in question has BIGINT columns that are read as Java longs, the comparisons will always fail, as the CSV data is read as ints.

**Comment by aarrsseni** [comment]
@andrus 
I tried to reproduce this bug. Seems that now it works. 
Maybe there is some special case?
I created table `channel.execStatement().exec("CREATE TABLE \"t5\" (\"c1\" BIGINT, \"c2\" VARCHAR(10))")`
Created csv: `"c1","c2"
1,"Test1"
2,"Test2"`
And test looks like this:
```
        T5.csvDataSet().load("classpath:io/bootique/jdbc/test/dataset/t5.csv").persist();
        List<Object[]> data = T5.select();
        assertEquals(2, data.size());

        data.sort(Comparator.comparing(r -> (Long) r[0]));

        Object[] row1 = data.get(0);
        assertTrue(row1[0] instanceof Long);
        assertEquals(1L, row1[0]);
        assertEquals("Test1", row1[1]);

        Object[] row2 = data.get(1);
        assertTrue(row2[0] instanceof Long);
        assertEquals(2L, row2[0]);
        assertEquals("Test2", row2[1]);
```

**Comment by andrus** [comment]
I just updated the original description. The problem is with `TableMatcher.assertMatchesCsv()` method. So yeah, `T5.select()` will retrieve the right data types, but when it is compared with CSV again, the CSV will be read with the wrong ones and the comparison will fail.

**Comment by andrus** [comment]
This works for BIGINT, and since https://github.com/bootique/bootique-jdbc/issues/116 was fixed - for BigDecimal.
