### ISSUE TITLE
Unify hikari and tomcat configurations

### ISSUE THREAD

**Issue by stariy95** [bootique/bootique-jdbc#94]
`HikariCPManagedDataSourceFactory` and `TomcatManagedDataSourceFactory` have different naming for essentially same configuration properties (e.g. `url` vs `jdbcUrl`). 
This may lead to unnecessary confusion.

On the other hand, current naming follows the native one for them. Unifying base parts of configs and leaving rest parts as is may lead to even more confusion for users.

**Comment by andrus** [comment]
Closing due to #132
